server:
  port: 9999
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: 123.56.168.25
      port: 6379
      database: 0
      password: Wei2793651330..
fdfs:
  thumb-image:
    width: 100
    height: 100
  tracker-list:
    - 123.56.168.25:22122
  connect-timeout: 5000
  so-timeout: 5000
  web-server-url: http://123.56.168.25/